[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
stakeguard = "4ixiwwbedA1p3s79zgPmqf9C2JKLJ1WkEDVtCw9yQSxf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/tmp/deploy-wallet.json"

[scripts]
test = "echo 'no tests'"
